filter:
    excluded_paths:
        - "tests/"
        - "js/"
        - "css/"
        - "bin/"

build:
    tests:
        override:
            -
                command:
                    - 'bash bin/install-wp-tests.sh wordpress_test root "" localhost latest'
                    - 'phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'