filter:
    excluded_paths:
        - "tests/"
        - "js/"
        - "css/"
        - "bin/"

build:
    environment:
        php: '5.6.16'
        mysql: true
        selenium: false
        postgresql: false
        redis: false

        variables:
            WP_VERSION: '4.6.1'
            WP_MULTISITE: '0'

    dependencies:
        before:
            - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

    cache:
          directories:
              - ~/Downloads/
    tests:
         override:
              -
                    command: 'phpunit --coverage-clover=coverage.xml'
                    idle_timeout: 1800
                    coverage:
                        file: 'coverage.xml'
                        format: 'php-clover'