language: php

# notifications:
#   email:
#     on_success: never
#     on_failure: change

branches:
  only:
    - master

php:
  - 5.3
#  - 5.4
#  - 5.5
#  - 5.6
#  - 7.0
#  - hhvm
#  - nightly

env:
 - WP_VERSION=latest WP_MULTISITE=0
#  - WP_VERSION=3.7 WP_MULTISITE=0
#  - WP_VERSION=4.6.1 WP_MULTISITE=0
#  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

#matrix:
#  include:
#    - php: 5.3
#      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test travis '' localhost $WP_VERSION
    #- wget https://raw.github.com/benbalter/wordpress-plugin-tests/setup/setup.sh
    #- source setup.sh

script: phpunit
